#pragma once

namespace UniqueCreator
{
    namespace Graphics
    {
        [uuid(BE4A9AB4-977F-4B2E-806E-3421557B561D)]
        [version(1.0)]
        interface IBackgroundSwapChainResources : IInspectable
        {

        };
    }
}
