#pragma once

import "PixelBuffer.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        interface IBackBuffer requires IPixelBuffer
        {
            void Dummy1();
        };
    }
}
