#pragma once

import "CopyGpuCommandContext.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        interface IComputeGpuCommandContext requires ICopyGpuCommandContext
        {
            void Dispatch();
        };
    }
}
