#pragma once

import "CopyGpuCommandContext.idl";
import "ComputePipelineState.idl";
import "GpuVirtualResource.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        interface IComputeGpuCommandContext requires ICopyGpuCommandContext
        {
			void SetComputeUAVBuffer(UInt32 slot, IGpuVirtualResource r);
            void SetPSO(ComputePipelineState pso);
            void Dispatch( UInt32 x, UInt32 y, UInt32 z);
        };
    }
}
