namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass ComputeShaderByteCode
        {
            ComputeShaderByteCode();
            Windows.Foundation.Collections.IVector<UInt8> Code;
        };
    }
}


