#pragma once

import "GraphicTypes.idl";
import "ResourceCreateContext.idl";
import "SwapChainResources.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass CompositionSwapChainResources : ISwapChainResources
        {
            CompositionSwapChainResources(ResourceCreateContext ctx, Windows.UI.Xaml.Controls.SwapChainPanel  panel);

            void SetCompositionScale(Single scaleX, Single scaleY);
            void SetLogicalSize(Size2D size);
            void SetDisplayInformation(Windows.Graphics.Display.DisplayInformation displayInformation);
        }
    }
}
