import "ComputeShaderByteCode.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass ComputePipelineStateDescription
        {
            ComputeShaderByteCode   CS;
        };
    }
}


