import "ComputePipelineStateDescription.idl";
import "ResourceCreateContext.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
		[default_interface]
        runtimeclass ComputePipelineState
        {
            ComputePipelineState(ResourceCreateContext ctx, ComputePipelineStateDescription d);
        };
    }
}


