#pragma once

import "GpuCommandContext.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        interface ICopyGpuCommandContext requires IGpuCommandContext
        {
            void Copy();
        };
    }
}
