
import "FenceHandle.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        [uuid(D1566F5D-3722-4F1C-A359-F6366164A1A4)]
        [exclusiveto(DirectQueue)]
        [version(1.0)]
        interface IDirectQueue : IInspectable
        {
            HRESULT WaitForIdleGpu();
            HRESULT WaitForFence(IFenceHandle v );
            HRESULT InsertWaitOn(IFenceHandle v );
        };

        [version(1.0)]
        [activatable(1.0)]
        runtimeclass DirectQueue
        {
            [default] interface IDirectQueue;
        }
    }
}


