#pragma once

import "ComputeGpuCommandContext.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        interface IDirectGpuCommandContext requires IComputeGpuCommandContext
        {
            void Draw();
        }
    }
}
