namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass DomainShaderByteCode
        {
            DomainShaderByteCode();
            Windows.Foundation.Collections.IVector<UInt8> Code;
        };
    }
}


