namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass GeometryShaderByteCode
        {
            GeometryShaderByteCode();
            Windows.Foundation.Collections.IVector<UInt8> Code;
        };
    }
}


