#pragma once

import "FenceHandle.idl";
import "GpuVirtualResource.idl";
import "GraphicTypes.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        interface IGpuCommandContext 
        {
            IFenceHandle Submit();
            void SubmitAndWaitToExecute();
            void TransitionResource( IGpuVirtualResource r, ResourceState old_state, ResourceState new_state );
        };
    }
}
