#pragma once

import "GraphicTypes.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        interface IGpuVirtualResource : IInspectable
        {
            GpuVirtualAddress VirtualAddress { get; };
        };
    }
}
