#pragma once

import "ComputeGpuCommandContext.idl";
import "GraphicsPipelineState.idl";
import "BackBuffer.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        interface IGraphicsGpuCommandContext requires IComputeGpuCommandContext
        {
			void SetGraphicsPipelineStateObject(GraphicsPipelineState pso);
            void Clear(IBackBuffer b);
            void Draw();
        }
    }
}
