#pragma once

import "ComputeGpuCommandContext.idl";
import "GraphicsPipelineState.idl";
import "BackBuffer.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        interface IGraphicsGpuCommandContext requires IComputeGpuCommandContext
        {
			void SetDescriptorHeaps();
			void SetGraphicsPipelineStateObject(GraphicsPipelineState pso);
            void Clear(IBackBuffer b);
			void SetPrimitiveTopology(PrimitiveTopology t);
            void Draw(UInt32 vertexCount, UInt32 vertexOffset);
        }
    }
}
