
import "GraphicTypes.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass InputLayoutDescription
        {
            Windows.Foundation.Collections.IVector<InputElementDescription> InputElementDescs;
        };
    }
}


