namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass PixelShaderByteCode
        {
            PixelShaderByteCode();
            Windows.Foundation.Collections.IVector<UInt8> Code;
        };
    }
}


