#pragma once

import "GpuVirtualResource.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        interface IPixelBuffer requires IGpuVirtualResource
        {
            Size2D Size2D{ get; };
            Size3D Size3D{ get; };
        };
    }
}
