#pragma once

import "GpuVirtualResource.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        [uuid(4B28DBAC-52F2-48C2-BFF4-CB1717EBD4B4)]
        [version(1.0)]
        interface IPixelBuffer : IInspectable requires IGpuVirtualResource
        {
        };
    }
}
