
import "GraphicTypes.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass PrimitiveRangeDescription
        {
            Windows.Foundation.Collections.IVector<InputElementDescription> Ranges;
        };
    }
}


