#pragma once

//import "DirectQueue.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass ResourceCreateContext
        {
            ResourceCreateContext();
            void Sync();
            void ResetViewDependentResources();
        }
    }
}
