#pragma once

import "DirectQueue.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass ResourceCreateContext;
        

        [exclusiveto(ResourceCreateContext)]
        [uuid(D5161D72-0BF4-4C7F-9401-879AA646BFA9)]
        [version(1.0)]
        interface IResourceCreateContext : IInspectable
        {
            HRESULT CreateDirectQueue( [out, retval] DirectQueue** value);

            HRESULT Sync();
            HRESULT ResetViewDependentResources();
        };

        [version(1.0)]
        [activatable(1.0)]
        runtimeclass ResourceCreateContext
        {
            [default] interface IResourceCreateContext;
        }
    }
}
