namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass RootSignatureByteCode
        {
            RootSignatureByteCode();
            Windows.Foundation.Collections.IVector<UInt8> Code;
        };
    }
}


