
import "GraphicTypes.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass StreamOutputDescription
        {
            Windows.Foundation.Collections.IVector<StreamOutputDeclarationEntry>    SODeclaration;
            Windows.Foundation.Collections.IVector<UInt32>                          BufferStrides;
            UInt32                                                                  RasterizedStream;
        };
    }
}


