
import "FenceHandle.idl";
import "DirectGpuCommandContext.idl";
import "BackBuffer.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        interface ISwapChainResources
        {
            void Resize( UInt32 width, UInt32 height );
            void SetSourceSize(UInt32 width, UInt32 height);
            void Present();


            void WaitForGpu();
            void WaitForFence(IFenceHandle v );
            void InsertWaitOn(IFenceHandle v );
            void Sync();
            void MoveToNextFrame();


            //
            //IDirectQueue               Queue{ get;  }

            //todo: change
            IDirectGpuCommandContext    CreateDirectCommandContext();

            //IGraphicsGpuCommandContext  CreateGraphicsCommandContext();
            IComputeGpuCommandContext   CreateComputeCommandContext();

            IBackBuffer BackBuffer{ get; };
        };
    }
}


