#pragma once
import "UniqueCreator.Graphics.Gpu.PixelBuffer.idl";
namespace UniqueCreator
{
    namespace Graphics
    {
        namespace Gpu
        {
            interface IColorBuffer requires IPixelBuffer
            {
				void Dummy1();
            };

			[default_interface]
            runtimeclass FrameColorBuffer : IColorBuffer
            {

            };

			[default_interface]
			runtimeclass ViewColorBuffer : IColorBuffer
			{

			};
        }
    }
}
