#pragma once
import "UniqueCreator.Graphics.Gpu.PixelBuffer.idl";
namespace UniqueCreator
{
    namespace Graphics
    {
		namespace Gpu
		{
			[default_interface]
			runtimeclass DepthBuffer : IPixelBuffer
			{
			};
		}
    }
}
