#pragma once

namespace UniqueCreator
{
    namespace Graphics
    {
        namespace Gpu
        {
        runtimeclass GeometryShaderByteCode
        {
            GeometryShaderByteCode();
            Windows.Foundation.Collections.IVector<UInt8> Code;
        };
        }
    }
}


