#pragma once

import "UniqueCreator.Graphics.Gpu.ComputeShaderByteCode.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        namespace Gpu
        {
        runtimeclass ComputePipelineStateDescription
        {
            ComputePipelineStateDescription();
            ComputeShaderByteCode               CS;
        };
        }
    }
}


