#pragma once

namespace UniqueCreator
{
    namespace Graphics
    {
        namespace Gpu
        {
        runtimeclass RootSignatureByteCode
        {
            RootSignatureByteCode();
            Windows.Foundation.Collections.IVector<UInt8> Code;
        };
        }
    }
}


