#pragma once

import "UniqueCreator.Graphics.Gpu.GraphicTypes.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        namespace Gpu
        {
            interface IVirtualResource 
            {
                GpuVirtualAddress VirtualAddress { get; };
            };

			interface IShaderResourceView
			{
				CpuDescriptorHandle SRV{ get; };
			};

			interface IUnorderedAccessView
			{
				CpuDescriptorHandle UAV{ get; };
			};
        }
    }
}
