#pragma once

namespace UniqueCreator
{
    namespace Graphics
    {
        namespace Gpu
        {
        runtimeclass ComputeShaderByteCode
        {
            ComputeShaderByteCode();
            Windows.Foundation.Collections.IVector<UInt8> Code;
        };
        }
    }
}


