#pragma once
import "UniqueCreator.Graphics.Gpu.PixelBuffer.idl";
namespace UniqueCreator
{
    namespace Graphics
    {
        namespace Gpu
        {
        interface IBackBuffer requires IPixelBuffer
        {
            void Dummy1();
        };
        }
    }
}
