#pragma once

namespace UniqueCreator
{
    namespace Graphics
    {
        namespace Gpu
        {
        runtimeclass VertexShaderByteCode
        {
            VertexShaderByteCode();
            Windows.Foundation.Collections.IVector<UInt8> Code;
        };
        }
    }
}


