#pragma once

import "UniqueCreator.Graphics.Gpu.GraphicsComputeCommandContext.idl";
import "UniqueCreator.Graphics.Gpu.ResourceCreateContext.idl";

namespace UniqueCreator
{
    namespace Graphics
    {
        namespace Gpu
        {
            struct Matrix44
            {
                Single r00;
                Single r01;
                Single r02;
                Single r03;

                Single r10;
                Single r11;
                Single r12;
                Single r13;

                Single r20;
                Single r21;
                Single r22;
                Single r23;

                Single r30;
                Single r31;
                Single r32;
                Single r33;
            };

            struct WorldTransform
            {
                Matrix44 Value;
            };

            struct CameraTransforms
            {
                Matrix44 ViewTransform;
                Matrix44 PerspectiveTransform;
            };

            struct PassView
            {
                Single Width;
                Single Height;
                Single MinimumZ;
                Single MaximumZ;
            };

            struct DepthPassData
            {
                CameraTransforms Camera;
                PassView         ViewPort;
            };

            struct AlbedoPassData
            {
                CameraTransforms Camera;
                PassView         ViewPort;
            };

            runtimeclass AlbedoPass
            {
                void AddInstance( DerivativesSkinnedModelInstance instance );
                void Submit( AlbedoPassData passData, IGraphicsComputeCommandContext ctx );
            }

            runtimeclass DepthPass
            {
                void AddInstance(DerivativesSkinnedModelInstance instance);
                void Submit(DepthPassData passData, IGraphicsComputeCommandContext ctx);
            }

            [default_interface]
            runtimeclass DerivativesSkinnedMaterial
            {
                DerivativesSkinnedMaterial( ResourceCreateContext rc, IGraphicsComputeCommandContext ctx, String payload );
                void SubmitDepth(DepthPassData p, IGraphicsComputeCommandContext d);
                void SubmitAlbedo(AlbedoPassData p, IGraphicsComputeCommandContext d);
            };

            [default_interface]
            runtimeclass DerivativesSkinnedModel
            {
                DerivativesSkinnedModel( DerivativesSkinnedMaterial material, ResourceCreateContext rc, IGraphicsComputeCommandContext ctx, String payload );
                void SubmitDepth(IGraphicsComputeCommandContext d);
                void SubmitAlbedo(IGraphicsComputeCommandContext d);
            };

            runtimeclass DerivativesSkinnedModelInstance
            {
                DerivativesSkinnedModelInstance(DerivativesSkinnedModel Model, Matrix44 instance);
                void SubmitDepth(IGraphicsComputeCommandContext d);
                void SubmitAlbedo(IGraphicsComputeCommandContext d);
            };

        }
    }
}


