namespace UniqueCreator
{
    namespace Graphics
    {
        runtimeclass VertexShaderByteCode
        {
            VertexShaderByteCode();
            Windows.Foundation.Collections.IVector<UInt8> Code;
        };
    }
}


